name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - feature
      - feat
      - enhancement
      - meta-enhancement
      - meta-feature
  - title: "🐛 Bug Fixes"
    labels:
      - fix
      - bugfix
      - bug
  - title: "🧰 Maintenance"
    label:
      - chore
      - dependencies
  - title: 📝 Documentation updates
    labels:
      - documentation
      - doc
      - meta-requires-doc
  - title: 🚦 Tests
    labels:
      - test
      - tests
autolabeler:
  - label: "chore"
    files:
      - "*.md"
    branch:
      - '/docs{0,1}\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "meta-enhancement"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - '/feat\/.+/'
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  # What's Changed

  $CHANGES
