name: Build/Publish on push

on:
  push:
    branches:
      - "*dev*"
      - "*master*"
      - "*main*"
    tags:
      - "*"
jobs:
  job1:
    name: build_and_release
    runs-on: windows-latest
    environment: production

    env:
      configuration: Release
      Main_Project: Ui/Ui.csproj
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      # Version
      - name: Get Version
        id: get_version
        run: ./scripts/Get-Version.ps1

      - name: Get Version1
        run: echo "V=${{steps.get_version.outputs.Version}}"
      - name: Get Version2
        run: echo "V=${{env.Version}}"