name: Test On Push[tag检测已失效]

on:
  push:
    branches:
      - "*"

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: "v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.checkTag.outputs.exists }}

      - name: run if tag exists
        if: steps.checkTag.outputs.exists == 'true'
        run: echo "tag exists"

      - name: Get tag
        if: steps.checkTag.outputs.exists == 'true'
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: run if tag exists
        if: steps.checkTag.outputs.exists == 'true'
        run: echo ${{ steps.get_version.outputs.VERSION }}
